functionsDirectory = "/Users/ydauber/Build/claude/gana/backend/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/ydauber/Build/claude/gana/backend/dist"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/ydauber/Build/claude/gana/backend"
command = "npm install && npx prisma generate && npm run build"
functions = "/Users/ydauber/Build/claude/gana/backend/netlify/functions"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]